### PR TITLE
Add Rollux and Syscoin safe deployments

### PR DESCRIPTION
**Pull request by fernando-syslabs**
Network: Rollux Mainnet
ChainID: 570
RPC endpoint: https://rpc.rollux.com/
Block explorer: https://explorer.rollux.com/

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-570.json

<hr/>

Network: Rollux Tanenbaum - Tesnet
ChainID: 57000
RPC endpoint: https://rpc-tanenbaum.rollux.com/
Block explorer: https://rollux.tanenbaum.io/

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-57000.json

<hr/>

Network: Syscoin Mainnet
ChainID: 57
RPC endpoint: https://rpc.syscoin.org/
Block explorer: https://explorer.syscoin.org/

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-57.json

<hr/>

Network: Syscoin Tanenbaum - Tesnet
ChainID: 5700
RPC endpoint: https://rpc.tanenbaum.io/
Block explorer: https://tanenbaum.io/

https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-5700.json

### CODE REVIEW

**Comment by moisses89** [comment]
@fernando-syslabs I couldn't find rollux mainnet in chainlist https://chainlist.org/chain/570 and also is not here https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-570.json

**Comment by develCuy** [comment]
@moisses89, we have the PR awaiting for the past couple week: https://github.com/ethereum-lists/chains/pull/2862 I hope they merge it soon

**Comment by fernando-syslabs** [comment]
@moisses89, ethereum-lists PR merged and Chainlist updating soon. All anything else for proceeding here?

**Comment by moisses89** [comment]
> @moisses89, ethereum-lists PR merged and Chainlist updating soon. Anything else for proceeding here?

Good to know :) 
Anyway looks like the rpc is not returning the contract code:
```
curl --location --request POST 'https://rpc.rollux.com/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
        "0x69f4D1788e39c87893C980c06EdF4b7f686e2938",
        "latest"
    ],
    "id": 1}'
```
```
{"jsonrpc":"2.0","id":1,"result":"0x"}
```
Could you review?

**Comment by develCuy** [comment]
@moisses89 we depend on this one too: https://github.com/safe-global/safe-singleton-factory/issues/153. We will ping you back when done.

**Comment by fernando-syslabs** [comment]
@moisses89  Contracts deployed

**Comment by develCuy** [comment]
Hi @moisses89, we sorry about that. There were a couple resets of mainnet prior to launch. Mainnet is ready now and RPC is up.

**Review by mmv08 — APPROVED** [review]

**Pull request merged**
