### PR TITLE
Add Candle chain

### PR DESCRIPTION
**Pull request by pkakelas**
Network Name: Candle
New RPC URL: https://rpc.cndlchain.com
Chain ID: 534
Currency Symbol (Optional): CNDL
Block Explorer URL: https://candleexplorer.com/

### CODE REVIEW

**Comment by samisbakedham** [comment]
+ 1 for adding Candle!

**Comment by CrystallineButterfly** [comment]
Thank you for creating my PR, after reviewing my PR to safe-contracts repo. 

Candle has been added!

All the best-K

**Review by CrystallineButterfly — COMMENTED** [review]
Thank you @pkakelas For the help with this, contact me and I will give you share of the dework bounty!

All the best-K

**Review by CrystallineButterfly — APPROVED** [review]

**Comment by moisses89** [comment]
Are the contracts deployed? I couldn't find them.

**Comment by CrystallineButterfly** [comment]
> Are the contracts deployed? I couldn't find them.

Yeah so @moisses89 The original deployment was at different addresses than the ones @pkakelas put in here, 
Should I add the original addresses instead of the ones on this commit?

**Comment by moisses89** [comment]
> > Are the contracts deployed? I couldn't find them.
> 
> Yeah so @moisses89 The original deployment was at different addresses than the ones @pkakelas put in here, 
> Should I add the original addresses instead of the ones on this commit? 
> 

No, the address are correct by the contracts are not deployed, I think that your previous address was wrong because use a incorrect tag version on safe-contracs.

**Comment by CrystallineButterfly** [comment]
@moisses89 

Ok, so I have done a second PR, which is on the correct tag-version for the contracts. Are the addresses good there? Here is the PR = #109

**Comment by moisses89** [comment]
> @moisses89
> 
> Ok, so I have done a second PR, which is on the correct tag-version for the contracts. Are the addresses good there? Here is the PR = #109
> 
> On this PR #109 I have also attached an image of the deployment of the gnosis safe contract seen on https://candleexplorer.com

When execute `yarn deploy-all custom` with the RPC configured on .env in this case `NODE_URL=https://rpc.cndlchain.com/` the result could be `deploying` if the contract is not deployed or `Reuse` if the contract is deployed. 
In this case the result is always deploying: 
```
deploying "SimulateTxAccessor" (tx: 0xd30275979127e344e10e2a73408e2079b3a171a8ce6d51cb63a6506b8151b228)...: deployed at 0x59AD6735bCd8152B84860Cb256dD9e96b85F69Da with 70370 gas
deploying "GnosisSafeProxyFactory" (tx: 0xa9408741d528466465187ec9fd5927aab53b265ba02684b74f3758aff24b464b)...: deployed at 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2 with 114780 gas
deploying "DefaultCallbackHandler" (tx: 0x0e917bcc222e1574a96127280ae3b1a50ce1cbf194fc9ff88672544f89d49c78)...: deployed at 0x1AC114C2099aFAf5261731655Dc6c306bFcd4Dbd with 90959 gas
deploying "CompatibilityFallbackHandler" (tx: 0xf4aa45761f9928f9cf810f367d83d55456f016ab0137563863567cf6983b78d0)...: deployed at 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4 with 141327 gas
deploying "CreateCall" (tx: 0x9fa6774c0faddfd778d163620879154278255bb6fdf0d01ba4eb0037eb3b319f)...: deployed at 0x7cbB62EaA69F79e6873cD1ecB2392971036cFAa4 with 73427 gas
deploying "MultiSend" (tx: 0xadee50454230b30f2c8a07fef0ef220e97ccdaaf829064f579bef5ba100834cf)...: deployed at 0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761 with 66746 gas
deploying "MultiSendCallOnly" (tx: 0xc76f498572230fffcba21af5b2c04199be34def951fcf5c597498876bf6febd2)...: deployed at 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D with 62765 gas
deploying "SignMessageLib" (tx: 0x4000d043aad36c13fb48b4a899475e8d331330e902c0ac0adfd1a1752e78df17)...: deployed at 0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2 with 71687 gas
deploying "GnosisSafeL2" (tx: 0xb3029f67e515c79802c77534b1a5bc0e7a13f2596aef3cf506027d572911b48a)...: deployed at 0x3E5c63644E683549055b9Be8653de26E0B4CD36E with 438141 gas
deploying "GnosisSafe" (tx: 0xb3084bc3e4f4dc089e26be0a61c44e7b7c8cd6feadad37b9ef367ae6249f21d0)...: deployed at 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552 with 424133 gas
```
The tx is ok in the blockexplorer but the contract is really never deployed.

**Comment by CrystallineButterfly** [comment]
Ok thank you 🙏 I will solve this and make sure the contracts deploy effectively.

All the best- K

**Comment by samisbakedham** [comment]
> > @moisses89
> 
> > 
> 
> > Ok, so I have done a second PR, which is on the correct tag-version for the contracts. Are the addresses good there? Here is the PR = #109
> 
> > 
> 
> > On this PR #109 I have also attached an image of the deployment of the gnosis safe contract seen on https://candleexplorer.com
> 
> 
> 
> When execute `yarn deploy-all custom` with the RPC configured on .env in this case `NODE_URL=https://rpc.cndlchain.com/` the result could be `deploying` if the contract is not deployed or `Reuse` if the contract is deployed. 
> 
> In this case the result is always deploying: 
> 
> ```
> 
> deploying "SimulateTxAccessor" (tx: 0xd30275979127e344e10e2a73408e2079b3a171a8ce6d51cb63a6506b8151b228)...: deployed at 0x59AD6735bCd8152B84860Cb256dD9e96b85F69Da with 70370 gas
> 
> deploying "GnosisSafeProxyFactory" (tx: 0xa9408741d528466465187ec9fd5927aab53b265ba02684b74f3758aff24b464b)...: deployed at 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2 with 114780 gas
> 
> deploying "DefaultCallbackHandler" (tx: 0x0e917bcc222e1574a96127280ae3b1a50ce1cbf194fc9ff88672544f89d49c78)...: deployed at 0x1AC114C2099aFAf5261731655Dc6c306bFcd4Dbd with 90959 gas
> 
> deploying "CompatibilityFallbackHandler" (tx: 0xf4aa45761f9928f9cf810f367d83d55456f016ab0137563863567cf6983b78d0)...: deployed at 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4 with 141327 gas
> 
> deploying "CreateCall" (tx: 0x9fa6774c0faddfd778d163620879154278255bb6fdf0d01ba4eb0037eb3b319f)...: deployed at 0x7cbB62EaA69F79e6873cD1ecB2392971036cFAa4 with 73427 gas
> 
> deploying "MultiSend" (tx: 0xadee50454230b30f2c8a07fef0ef220e97ccdaaf829064f579bef5ba100834cf)...: deployed at 0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761 with 66746 gas
> 
> deploying "MultiSendCallOnly" (tx: 0xc76f498572230fffcba21af5b2c04199be34def951fcf5c597498876bf6febd2)...: deployed at 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D with 62765 gas
> 
> deploying "SignMessageLib" (tx: 0x4000d043aad36c13fb48b4a899475e8d331330e902c0ac0adfd1a1752e78df17)...: deployed at 0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2 with 71687 gas
> 
> deploying "GnosisSafeL2" (tx: 0xb3029f67e515c79802c77534b1a5bc0e7a13f2596aef3cf506027d572911b48a)...: deployed at 0x3E5c63644E683549055b9Be8653de26E0B4CD36E with 438141 gas
> 
> deploying "GnosisSafe" (tx: 0xb3084bc3e4f4dc089e26be0a61c44e7b7c8cd6feadad37b9ef367ae6249f21d0)...: deployed at 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552 with 424133 gas
> 
> ```
> 
> The tx is ok in the blockexplorer but the contract is really never deployed. 
> 
> 

What do you mean?

**Comment by CrystallineButterfly** [comment]
> > > @moisses89
> > 
> > 
> > > 
> > 
> > 
> > > Ok, so I have done a second PR, which is on the correct tag-version for the contracts. Are the addresses good there? Here is the PR = #109
> > 
> > 
> > > 
> > 
> > 
> > > On this PR #109 I have also attached an image of the deployment of the gnosis safe contract seen on https://candleexplorer.com
> > 
> > 
> > When execute `yarn deploy-all custom` with the RPC configured on .env in this case `NODE_URL=https://rpc.cndlchain.com/` the result could be `deploying` if the contract is not deployed or `Reuse` if the contract is deployed.
> > In this case the result is always deploying:
> > ```
> > 
> > deploying "SimulateTxAccessor" (tx: 0xd30275979127e344e10e2a73408e2079b3a171a8ce6d51cb63a6506b8151b228)...: deployed at 0x59AD6735bCd8152B84860Cb256dD9e96b85F69Da with 70370 gas
> > 
> > deploying "GnosisSafeProxyFactory" (tx: 0xa9408741d528466465187ec9fd5927aab53b265ba02684b74f3758aff24b464b)...: deployed at 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2 with 114780 gas
> > 
> > deploying "DefaultCallbackHandler" (tx: 0x0e917bcc222e1574a96127280ae3b1a50ce1cbf194fc9ff88672544f89d49c78)...: deployed at 0x1AC114C2099aFAf5261731655Dc6c306bFcd4Dbd with 90959 gas
> > 
> > deploying "CompatibilityFallbackHandler" (tx: 0xf4aa45761f9928f9cf810f367d83d55456f016ab0137563863567cf6983b78d0)...: deployed at 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4 with 141327 gas
> > 
> > deploying "CreateCall" (tx: 0x9fa6774c0faddfd778d163620879154278255bb6fdf0d01ba4eb0037eb3b319f)...: deployed at 0x7cbB62EaA69F79e6873cD1ecB2392971036cFAa4 with 73427 gas
> > 
> > deploying "MultiSend" (tx: 0xadee50454230b30f2c8a07fef0ef220e97ccdaaf829064f579bef5ba100834cf)...: deployed at 0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761 with 66746 gas
> > 
> > deploying "MultiSendCallOnly" (tx: 0xc76f498572230fffcba21af5b2c04199be34def951fcf5c597498876bf6febd2)...: deployed at 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D with 62765 gas
> > 
> > deploying "SignMessageLib" (tx: 0x4000d043aad36c13fb48b4a899475e8d331330e902c0ac0adfd1a1752e78df17)...: deployed at 0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2 with 71687 gas
> > 
> > deploying "GnosisSafeL2" (tx: 0xb3029f67e515c79802c77534b1a5bc0e7a13f2596aef3cf506027d572911b48a)...: deployed at 0x3E5c63644E683549055b9Be8653de26E0B4CD36E with 438141 gas
> > 
> > deploying "GnosisSafe" (tx: 0xb3084bc3e4f4dc089e26be0a61c44e7b7c8cd6feadad37b9ef367ae6249f21d0)...: deployed at 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552 with 424133 gas
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The tx is ok in the blockexplorer but the contract is really never deployed.
> 
> What do you mean?

@samisbakedham I will solve this, I open a new PR and will make sure that one is approved. 

All the best-K

**Comment by samisbakedham** [comment]
This is solved now by the way @moisses89

**Comment by andreistefanwork** [comment]
Hi @moisses89.

I deployed the contracts myself on 23 August, for me the result was "deployed" for all contracts:

```
deployed "SimulateTxAccessor" (tx: 0xd481eb4a3b6ce7a0429a98a157fecb80cd4f942628109282a94aa556dc0f7013)...: deployed at 0x59AD6735bCd8152B84860Cb256dD9e96b85F69Da with 70370 gas
deployed "GnosisSafeProxyFactory" (tx: 0x16ed154f99e9a0ae46b0672ca26a5669f237fcd8bd861827dc7c34fc3db0918e)...: deployed at 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2 with 114780 gas
deployed "DefaultCallbackHandler" (tx: 0x35fe356510bb066a28130698c2c3887d39dad5559314e51a95e01af67ece1fed)...: deployed at 0x1AC114C2099aFAf5261731655Dc6c306bFcd4Dbd with 90959 gas
deployed "CompatibilityFallbackHandler" (tx: 0xe78492cbc8b9e3af6e9adedee3e4c375a0e2a0a22cb0fcde81d71bf4c325c2a9)...: deployed at 0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4 with 141327 gas
deployed "CreateCall" (tx: 0x3f22a3f0d2aa32a8e33c236c3f2acc7c5b7637d9d03cb72761c57d756266b39f)...: deployed at 0x7cbB62EaA69F79e6873cD1ecB2392971036cFAa4 with 73427 gas
deployed "MultiSend" (tx: 0xd4a30a45523d8d6de1f522d079f82ed6f1263662b3ef86acf73202e098604398)...: deployed at 0xA238CBeb142c10Ef7Ad8442C6D1f9E89e07e7761 with 66746 gas
deployed "MultiSendCallOnly" (tx: 0xb67c293cd1be2b850191e091c9c91f6462da610720fec7157197431944a4bc33)...: deployed at 0x40A2aCCbd92BCA938b02010E17A5b8929b49130D with 62765 gas
deployed "SignMessageLib" (tx: 0x396a2f2b2bb0b188279a3e5ac8dc740e98239f683f11492721120099432374f4)...: deployed at 0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2 with 71687 gas
deployed "GnosisSafeL2" (tx: 0x4accb4bb9d1ee0d77bbd0714f954fff784e82095103c61bae5f8e261a721d270)...: deployed at 0x3E5c63644E683549055b9Be8653de26E0B4CD36E with 438141 gas
deployed "GnosisSafe" (tx: 0x91491b0be6c99daba0df48b9c98a76fcd87bd72cb4702f9a565a5d75b5564428)...: deployed at 0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552 with 424133 gas
```


For the etherscan-verify step, I got the following result:
https://media.discordapp.net/attachments/1008686772982657105/1011706783393386646/unknown.png?width=1728&height=1302

However, if I try to lookup the GnosisSafeL2 contract in the block explorer, it shows up as an external address, instead of a smart contract address, with the deployed bytecode info, etc. => https://candleexplorer.com/address/0x3E5c63644E683549055b9Be8653de26E0B4CD36E

Now we also spinned up the react app and backend services. If I try to create a new Safe in the app, at the last step after transaction was successful, the react app tries to obtain the address of the newly created safe
(https://github.com/safe-global/safe-react/blob/58b7281ad7b990218bcdbb0efa91e94be9a8d307/src/routes/opening/index.tsx#L209)

And it fails, receipt.events property doesn't exist, and receipt.logs are empty

What do you think the issue might be here?

**Comment by CrystallineButterfly** [comment]
Hello there @andreistefanwork 

The first deployment happened on Monday, I deployed via yarn deploy-all custom: but as had verification errors didn't think it deployed, so tried to deploy again. So if you also deployed on 23rd. And then there's been a few other deployments since then, could this be why we have issues?

**Comment by moisses89** [comment]
The issue is that there aren't any contract deployed in the candle blockchain. 
For example if we request to the RPC_NODE the op_code of the contract in the address `0x3E5c63644E683549055b9Be8653de26E0B4CD36E` (safe_L2)
```
curl --location --request POST 'https://rpc.cndlchain.com' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
        "0x3E5c63644E683549055b9Be8653de26E0B4CD36E",
        "latest"
    ],
    "id": 1
}'
```
The address has not any code, is empty:
`{"jsonrpc":"2.0","id":1,"result":"0x"}%   `

I don't know the reason, but I think that the reason is out of the scope of this project and shouldn't be discussed here.

**Comment by CrystallineButterfly** [comment]
> The issue is that there aren't any contract between the addresses shared deployed in the candle blockchain or the RPC is not returning the op_code. For example if we request to the RPC_NODE the op_code of the contract in the address `0x3E5c63644E683549055b9Be8653de26E0B4CD36E` (safe_L2)
> 
> ```
> curl --location --request POST 'https://rpc.cndlchain.com' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "jsonrpc": "2.0",
>     "method": "eth_getCode",
>     "params": [
>         "0x3E5c63644E683549055b9Be8653de26E0B4CD36E",
>         "latest"
>     ],
>     "id": 1
> }'
> ```
> 
> The address has not any code, is empty: `{"jsonrpc":"2.0","id":1,"result":"0x"}% `
> 
> I don't know the reason, but I think that the reason is out of the scope of this project and shouldn't be discussed here.

Ok, I will look into this, thank you. 

All the best-K

**Comment by moisses89** [comment]
> > The issue is that there aren't any contract between the addresses shared deployed in the candle blockchain or the RPC is not returning the op_code. For example if we request to the RPC_NODE the op_code of the contract in the address `0x3E5c63644E683549055b9Be8653de26E0B4CD36E` (safe_L2)
> > ```
> > curl --location --request POST 'https://rpc.cndlchain.com' \
> > --header 'Content-Type: application/json' \
> > --data-raw '{
> >     "jsonrpc": "2.0",
> >     "method": "eth_getCode",
> >     "params": [
> >         "0x3E5c63644E683549055b9Be8653de26E0B4CD36E",
> >         "latest"
> >     ],
> >     "id": 1
> > }'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The address has not any code, is empty: `{"jsonrpc":"2.0","id":1,"result":"0x"}% `
> > I don't know the reason, but I think that the reason is out of the scope of this project and shouldn't be discussed here.
> 
> Ok, I will look into this, thank you.
> 
> All the best-K

Ok, but no new PR is necessary, only comment here when the contracts are really deployed :)

**Comment by CrystallineButterfly** [comment]
> > > The issue is that there aren't any contract between the addresses shared deployed in the candle blockchain or the RPC is not returning the op_code. For example if we request to the RPC_NODE the op_code of the contract in the address `0x3E5c63644E683549055b9Be8653de26E0B4CD36E` (safe_L2)
> > > ```
> > > curl --location --request POST 'https://rpc.cndlchain.com' \
> > > --header 'Content-Type: application/json' \
> > > --data-raw '{
> > >     "jsonrpc": "2.0",
> > >     "method": "eth_getCode",
> > >     "params": [
> > >         "0x3E5c63644E683549055b9Be8653de26E0B4CD36E",
> > >         "latest"
> > >     ],
> > >     "id": 1
> > > }'
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The address has not any code, is empty: `{"jsonrpc":"2.0","id":1,"result":"0x"}% `
> > > I don't know the reason, but I think that the reason is out of the scope of this project and shouldn't be discussed here.
> > 
> > 
> > Ok, I will look into this, thank you.
> > All the best-K
> 
> Ok, but no new PR is necessary, only comment here when the contracts are really deployed :)

Ok thank you :)

**Comment by samisbakedham** [comment]
Fixed

**Comment by moisses89** [comment]
> Fixed

Did you try this? and return the op_code?
```
curl --location --request POST 'https://rpc.cndlchain.com' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getCode",
    "params": [
        "0x3E5c63644E683549055b9Be8653de26E0B4CD36E",
        "latest"
    ],
    "id": 1
}'
```
I can't see any contract in this address for example https://candleexplorer.com/address/0xf48f2B2d2a534e402487b3ee7C18c33Aec0Fe5e4

**Comment by samisbakedham** [comment]
Hi: update this has been fixed and can now be merged. Test it [here](https://safe.candlelabs.org).

**Review by samisbakedham — APPROVED** [review]

**Comment by pkakelas** [comment]
I'm really sorry Moisses for the noisy PR. I just updated the contracts.

**Comment by moisses89** [comment]
@pkakelas how do you deploy this contracts aren't the deterministic addresses.

**Comment by samisbakedham** [comment]
> @pkakelas how do you deploy this contracts aren't the deterministic addresses. 
> 
> 

Just turned off the deterministic

**Comment by pkakelas** [comment]
I really appreciate the job you put into debugging the deployment and I'm really sorry for all the spamming of this PR. It seems that this network is a total scam, so I'm closing this PR. Keep up the great job folks!

**Pull request closed without merging**
