### PR TITLE
feat: add 1.4.1 canonical contracts for Plume

### PR DESCRIPTION
**Pull request by eyqs**
## Add new chain

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 98865

Provide RPC URL for the chain (should be able to query at least 3+ requests per second for automatic PR check).
- RPC_URL: https://rpc.plumenetwork.xyz

Relevant information:
- https://github.com/safe-global/safe-singleton-factory/pull/793
- Block explorer: https://explorer.plumenetwork.xyz

### CODE REVIEW

**Comment by mmv08** [comment]
ERROR: chain is not registered on Chainlist

**Comment by eyqs** [comment]
@mmv08 @remedcu Would it be possible to deploy using the RPC URL with an API key here rather than the public RPC on Chainlist? We are gating access behind an API key before the mainnet launch: https://phoenix-rpc.plumenetwork.xyz/FH7uok8YdCXHhBu4B18j632wpHogyMYan

**Comment by remedcu** [comment]
You can deploy the contracts by following the steps mentioned here: https://github.com/safe-global/safe-smart-account/tree/v1.4.1-3

**Review by remedcu — APPROVED** [review]
Running manually:

```
npm run review:verify-deployment -s -- --version "v1.4.1" --chainId 98865 --rpc "https://phoenix-rpc.plumenetwork.xyz/FH7uok8YdCXHhBu4B18j632wpHogyMYan" --verbose
Parsed options:
{
  version: 'v1.4.1',
  chainId: '98865',
  rpc: 'https://phoenix-rpc.plumenetwork.xyz/',
  verbose: true
}
chain 98865 exists on Chainlist
RPC reported chain 98865
CompatibilityFallbackHandler deployments:
• canonical deployment OK
CreateCall deployments:
• canonical deployment OK
MultiSend deployments:
• canonical deployment OK
MultiSendCallOnly deployments:
• canonical deployment OK
Safe deployments:
• canonical deployment OK
SafeL2 deployments:
• canonical deployment OK
SafeMigration deployments:
• canonical deployment OK
SafeProxyFactory deployments:
• canonical deployment OK
SafeToL2Migration deployments:
• canonical deployment OK
SafeToL2Setup deployments:
• canonical deployment OK
SignMessageLib deployments:
• canonical deployment OK
SimulateTxAccessor deployments:
• canonical deployment OK
```

**Comment by eyqs** [comment]
Thank you very much!

**Comment by eyqs** [comment]
Hey @remedcu - would you be able to edit your comment above to remove the API key in the RPC URL after https://phoenix-rpc.plumenetwork.xyz ? Thank you very much!

**Pull request merged**
