### PR TITLE
feat: add 1.4.1 contracts on viction

### PR DESCRIPTION
**Pull request by vickyvickydev**
## Add new chain

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 88

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
- RPC_URL: https://rpc.viction.xyz

Relevant information:
- safe-singleton-factory issue: https://github.com/safe-global/safe-singleton-factory/issues/717
- explorer: https://vicscan.xyz/
- deployment logs:
```
deploying "SimulateTxAccessor" (tx: 0x37e85619ef6681f085f510d890bb0b248bf38bd697d47eb376fca711daf01586)...: deployed at 0x3d4BA2E0884aa488718476ca2FB8Efc291A46199 with 282175 gas
deploying "SafeProxyFactory" (tx: 0xf6b05b287e914802caf5f063142d021234f143b6e4f9e38c39f159eae661502f)...: deployed at 0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67 with 860836 gas
deploying "TokenCallbackHandler" (tx: 0xc82fc0a10f4af1554766ef6cc55a8f3d38750ff429e7337f5d21cce8a952889d)...: deployed at 0xeDCF620325E82e3B9836eaaeFdc4283E99Dd7562 with 541740 gas
deploying "CompatibilityFallbackHandler" (tx: 0xc906f35c5bc7ea7ee691a32ec8d0ebb997e6501df7ec1db4ddb192a9320e6630)...: deployed at 0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99 with 1543296 gas
deploying "CreateCall" (tx: 0xc300c81756e19baa2d40dc9d15f0a45f4fd0b41e0c52d25758cfede7db9c2de5)...: deployed at 0x9b35Af71d77eaf8d7e40252370304687390A1A52 with 343126 gas
deploying "MultiSend" (tx: 0x30f47d48639fe6ae06d082cefce2d95c63454308b8c53f8b6f56a5ba0cb6fe57)...: deployed at 0x38869bf66a61cF6bDB996A6aE40D5853Fd43B526 with 222880 gas
deploying "MultiSendCallOnly" (tx: 0x60ccee1f9bfaa25f0edaf8d86f12cd02bcf9782d4d79c1e8eec1eb54bca4aa55)...: deployed at 0x9641d764fc13c8B624c04430C7356C1C7C8102e2 with 163130 gas
deploying "SignMessageLib" (tx: 0x08c0227ad19e664118f8f91fa726cd620eab1cb7abc0f0c9dd609b281b4b5791)...: deployed at 0xd53cd0aB83D845Ac265BE939c57F53AD838012c9 with 311441 gas
deploying "SafeToL2Setup" (tx: 0x40b1d103371108e6a480c7d35f60c3afc6754ab65a6ae185370f64bac89de915)...: deployed at 0xBD89A1CE4DDe368FFAB0eC35506eEcE0b1fFdc54 with 271105 gas
deploying "Safe" (tx: 0x9a1087f9984ef15e44cd5286abb479699381cbd6693d27075b7f74e3b678c63a)...: deployed at 0x41675C099F32341bf84BFc5382aF534df5C7461a with 6219098 gas
deploying "SafeL2" (tx: 0xb47ad57c61d26109fcdd50049a34cc3dfc4838daa1baa02b0dd7f846914001bf)...: deployed at 0x29fcB43b46531BcA003ddC8FCB67FFE91900C762 with 6444873 gas
deploying "SafeToL2Migration" (tx: 0xf7ab6a319d5f40fc6e70b8ceef402bc815f037bf5229f9add8a7ed01ea04f7e4)...: deployed at 0xfF83F6335d8930cBad1c0D439A841f01888D9f69 with 1548120 gas
deploying "SafeMigration" (tx: 0xdf503c1b9d01c4d0a07d0dfb4881b8c1417c8b1c56ba535ffbf5b2ea1cb57daa)...: deployed at 0x526643F69b81B008F46d95CD5ced5eC0edFFDaC6 with 624438 gas
```

### CODE REVIEW

**Comment by remedcu** [comment]
Could you also please add the deployment details for the Migration contracts? (I see that they are already deployed.)

**Comment by vickyvickydev** [comment]
Sorry, I'm not sure what you meant by that? The only thing I do to deploy is follow this repo's steps: https://github.com/safe-global/safe-smart-account/

**Comment by mmv08** [comment]
> Sorry, I'm not sure what you meant by that? The only thing I do to deploy is follow this repo's steps: https://github.com/safe-global/safe-smart-account/

You didn't include edit assets for Migration contracts but deployed them. Please include them in the JSON files as well.

**Comment by vickyvickydev** [comment]
> You didn't edit assets for Migration contracts but deployed them. Please include them in the JSON files as well.

Whoops, my bad. Added.

**Review by remedcu — APPROVED** [review]

**Pull request merged**
