### PR TITLE
Feature: Switch v1.4.1 to released

### PR DESCRIPTION
**Pull request by mmv08**
This PR:
- Switches the released flag for 1.4.1 to true
- Adjusts tests that checked that the latest returned version was 1.3.0

### CODE REVIEW

**Review by rmeissner — APPROVED** [review]
What impact does this have on the interface that use this (i.e. Safe Wallet)? Would they start creating Safes with the new version?

**Comment by mmv08** [comment]
@rmeissner:
>We have a global constant (set to 1.3.0) that we filter by. However, [some places](https://github.com/safe-global/web-core/blob/dev/src/services/contracts/safeContracts.ts) just filter by network. We could ensure everywhere relevant uses the constant and/or the released flag though.

That's their latest update from 3 months ago. I will double check with the web team before releasing

**Comment by liliya-soroka** [comment]
@mmv08 , did you check the impact with the mobile team too ?

**Comment by katspaugh** [comment]
This is definitely a breaking change for us. Should have been a major version, not a patch version. I've fixed it in the linked PR for multisends. Need to check other contracts too.

**Pull request merged**
