### PR TITLE
chore: add chain OORT Mainnet

### PR DESCRIPTION
**Pull request by molecula451**
## Add new chain

> Template to provide information about the new chain. Only add extra information in the bottom section. Ensure that the contracts are deployed on the chain, if not deploy with [safe-contracts](https://github.com/safe-global/safe-contracts). Only **one** chain ID, **one** Safe version and **one** deployment type per PR. This entire paragraph should be deleted.

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 970

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
- RPC_URL: https://mainnet-rpc.oortech.com

Relevant information:
Add any other relevant information like blockexplorer, any annotation...

https://mainnet-scan.oortech.com

### CODE REVIEW

**Comment by remedcu** [comment]
It looks like some contracts were not deployed, please check the `Review` check to see the same. Also, could you deploy the Migration contracts as well?

**Comment by molecula451** [comment]
> It looks like some contracts were not deployed, please check the `Review` check to see the same. Also, could you deploy the Migration contracts as well?

Thanks @remedcu for being aware of the PR according to the the "review" on the CI it seems its trying to look contracts at

image

but you can see here at the ABI file

image

the contract was deployed to another address, should i re-deploy ALL the contracts?

**Comment by mmv08** [comment]
> > It looks like some contracts were not deployed, please check the `Review` check to see the same. Also, could you deploy the Migration contracts as well?
> 
> Thanks @remedcu for being aware of the PR according to the the "review" on the CI it seems its trying to look contracts at
> 
> image
> 
> but you can see here at the ABI file
> 
> image
> 
> the contract was deployed to another address, should i re-deploy ALL the contracts?

this contracts are deployed deterministically, and the deployment should result in the addresses from the deployment file. If it was deployed to a different address, then something was wrong during the deployment (wrong tag used, there was a code change, etc)

**Comment by molecula451** [comment]
i re-ran the script with the latest package:

image

which includes OORT Mainnet

some contracts are getting reuse as you can see

image


looks like it re-deploy, the contract has not getting change and obviously it using the default compiler etc provided by the repo, nothing is changed

**Comment by molecula451** [comment]
Hey team this is fixed! i've added the new address, now the deployments are in the correct address as the scripts runs with no further issues

CompatiblityHandler: https://mainnet-scan.oortech.com/address/0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99

**Comment by molecula451** [comment]
[Screencast from 09-10-24 18:44:16.webm](https://github.com/user-attachments/assets/1e8b32c8-af39-4f65-b025-d2da4f52541c)

**Review by remedcu — APPROVED** [review]

**Comment by molecula451** [comment]
Hey team any chance that we look into merge this other PR? thanks https://github.com/safe-global/safe-eth-py/issues/1379#issuecomment-2411952202

**Comment by molecula451** [comment]
Hey team somehow im keep getting this issue trying to set up the safe-web

No Safe deployment found: https://github.com/safe-global/safe-wallet-web/issues/4415#issuecomment-2439741980

why is this? other chains work on the local instance (dockerized) safe-transaction service

**Pull request merged**
