### PR TITLE
Add ApeChain addresses

### PR DESCRIPTION
**Pull request by joescherping**
## Add new chain

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 33139

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
- RPC_URL: https://apechain.calderachain.xyz/http

Relevant information:
- Block explorer: https://apescan.io/

### CODE REVIEW

**Comment by remedcu** [comment]
Looks like the chain is not registered in chainlist: https://chainlist.org/chain/33139

**Comment by joescherping** [comment]
Adding it to chainlist now 👍

**Comment by bjp333** [comment]
https://chainlist.org/?search=33139  Can verify that it's now on Chainlist under Ape-mainnet

**Comment by joescherping** [comment]
Ah hmm someone else must've added it to chainlist and beat me to it

Well all the Safe contracts should be deployed and verified so let me know if there's anything else that needs to be done

Example: https://apescan.io/address/0x017062a1de2fe6b99be3d9d37841fed19f573804#code

**Review by remedcu — APPROVED** [review]

**Comment by 0xm1kr** [comment]
Hey @remedcu, will this PR also add ApeChain to the Gnosis Safe web app network list?

**Comment by remedcu** [comment]
@0xm1kr this PR only adds the ape chain address to this repo. For safe web apps, we only support limited networks natively.

**Comment by 0xm1kr** [comment]
> @0xm1kr this PR only adds the ape chain address to this repo. For safe web apps, we only support limited networks natively.

Thanks @remedcu - do you have any recommendations for the quickest approach to a UI for Safes on ApeChain?

**Pull request merged**
