### PR TITLE
feat: add Algen L1 mainnet(8911)

### PR DESCRIPTION
**Pull request by LuxesOwen**
## Add new chain

> Template to provide information about the new chain. Only add extra information in the bottom section. Ensure that the contracts are deployed on the chain, if not deploy with [safe-contracts](https://github.com/safe-global/safe-contracts). This entire paragraph can be deleted.

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID:  8911

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
- RPC_URL:  https://rpc.algen.network

Relevant information:
Add any other relevant information like blockexplorer, any annotation...

### CODE REVIEW

**Comment by nlordell** [comment]
It looks like this PR formats files differently to what we expect.

**Review by nlordell — CHANGES_REQUESTED** [review]
It looks like this PR formats files differently to what we expect. Please fix the formatting :)

**Comment by LuxesOwen** [comment]
Chain_ID: 8911
RPC_URL: https://rpc.algen.network/

**Comment by mmv08** [comment]
> Chain_ID: 8911 RPC_URL: https://rpc.algen.network/

Could you please check the message above?

**Comment by remedcu** [comment]
Closing due to inactivity.

**Pull request closed without merging**
