### PR TITLE
feat: add Bitrock Mainnet

### LINKED ISSUE #410: [New chain]: Bitrock Mainnet
### ChainId

7171

### Chainlist

https://chainlist.org/chain/7171

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.4.1

### Relevant information

RPC URL: https://connect.bit-rock.io
SYMBOL: BROCK

### PR DESCRIPTION
**Pull request by BCrypto-dev**
Fix [#410](https://github.com/safe-global/safe-deployments/issues/410)

### CODE REVIEW

**Comment by nlordell** [comment]
Can you please resolve the merge conflicts?

**Comment by BCrypto-dev** [comment]
> Can you please resolve the merge conflicts?

Done!

**Comment by BCrypto-dev** [comment]
I can not found the contract addresses in the bitrock mainnet after deploy, any thoughts about it?


PS. See script output below.

```
deploying "SimulateTxAccessor" (tx: 0x77b7bcfb7a08688880c59494a5b6185802e34f228b743f75465dfcb7f6a20cac)...: deployed at 0x3d4BA2E0884aa488718476ca2FB8Efc291A46199 with 237871 gas
deploying "SafeProxyFactory" (tx: 0xfabbd11b600aac83203b0800617033b32208a16645bdb81c6a11486c780e665f)...: deployed at 0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67 with 712428 gas
deploying "TokenCallbackHandler" (tx: 0xe5047db7ad7a9f8b7f312135619c3c87872548028587e1fd4b30c2da4b51a75c)...: deployed at 0xeDCF620325E82e3B9836eaaeFdc4283E99Dd7562 with 453288 gas
deploying "CompatibilityFallbackHandler" (tx: 0xbf170632106430c9926d6603765ce2cf92fdc88f8e19222b155686a3559d8f8b)...: deployed at 0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99 with 1269776 gas
deploying "CreateCall" (tx: 0xe04979ed687217ea22758c4ca61adec3994d27eaab76755434490082e55be61e)...: deployed at 0x9b35Af71d77eaf8d7e40252370304687390A1A52 with 290398 gas
deploying "MultiSend" (tx: 0x9127974f2fe58b587c0e3c8b7ebfc84fbc20c96054ee8c10b1b0c89e0c4a7334)...: deployed at 0x38869bf66a61cF6bDB996A6aE40D5853Fd43B526 with 190016 gas
deploying "MultiSendCallOnly" (tx: 0x258b71e2486ec8ac8ce874b731d429204b229d1d1679a92101b18691371d75d8)...: deployed at 0x9641d764fc13c8B624c04430C7356C1C7C8102e2 with 142122 gas
deploying "SignMessageLib" (tx: 0xb45b62b7ace40e3b5c11e8904a3164c4b50641fb4f280a59b81b1fc4555fcca9)...: deployed at 0xd53cd0aB83D845Ac265BE939c57F53AD838012c9 with 262353 gas
deploying "SafeL2" (tx: 0x66faafb0b681af6165759018df2bd6916010bb01663c1f3a030c44921cbd96f5)...: deployed at 0x29fcB43b46531BcA003ddC8FCB67FFE91900C762 with 5331001 gas
deploying "Safe" (tx: 0x095cdac566e066ab50242db042180bcf9a56b0df4ce01fac4709b107a94acf41)...: deployed at 0x41675C099F32341bf84BFc5382aF534df5C7461a with 5148594 gas
```

**Comment by nlordell** [comment]
Hmm, something is up with the PR. It is adding many more networks than 7171...

**Comment by BCrypto-dev** [comment]
> Hmm, something is up with the PR. It is adding many more networks than 7171...

Because I did a git rebase to fix the merge conflicts with **safe-global:main**. If it is needed I can open a new PR.

**Pull request closed without merging**
