### PR TITLE
feat: Add EclipseChain Testnet V1.4.1 contracts

### PR DESCRIPTION
**Pull request by margin-hub**
- Relevant issue: https://github.com/safe-global/safe-deployments/issues/487

### CODE REVIEW

**Comment by nlordell** [comment]
LGTM, I'm getting 502 server errors from the RPC endpoint when trying to verify the deployments. I will try again later.

**Comment by happyleow** [comment]
> LGTM, I'm getting 502 server errors from the RPC endpoint when trying to verify the deployments. I will try again later.

@nlordell Thanks for your response, I just checked that our RPC endpoint is working without any issues.(I deployed a new contract using the RPC endpoint)
I would like you to share more details about the RPC Endpoint issue so we can look into it together.
Yes, I hope you can try again.

**Review by nlordell — APPROVED** [review]

**Comment by happyleow** [comment]
@nlordell Thank you for merging my PRs.
Could you share the anticipated timeframe for releasing the new `safe-deployment` version?

**Comment by nlordell** [comment]
As per the [README](https://github.com/safe-global/safe-deployments?tab=readme-ov-file#release-cycle):

> `safe-deployments` release cycle is once per month, except urgent issues that require immediate attention.

The last release was last week, the next planned release is end of May. Let me know if there is urgency to the request, and we can move up the timeframe if needed.

**Comment by happyleow** [comment]
@nlordell Thanks for sharing the info.
This is a high priority for us.
We want to integrate the multi-sig Gnosis wallet onto our Eclipse Testnet as soon as possible.
Ideally, we'd like to expedite the timeframe, so please advise on any steps we can take to accelerate this integration.
Thank you for your support.

**Comment by nlordell** [comment]
I published a new version https://www.npmjs.com/package/@safe-global/safe-deployments/v/1.36.0

**Comment by happyleow** [comment]
@nlordell Oh great, thank you!!!

**Pull request merged**
