### PR TITLE
feat: add Bitrock Mainnet 1.4.1 contracts

### LINKED ISSUE #410: [New chain]: Bitrock Mainnet
### ChainId

7171

### Chainlist

https://chainlist.org/chain/7171

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.4.1

### Relevant information

RPC URL: https://connect.bit-rock.io
SYMBOL: BROCK

### PR DESCRIPTION
**Pull request by BCrypto-dev**
Fix [#410](https://github.com/safe-global/safe-deployments/issues/410)

### CODE REVIEW

**Comment by BCrypto-dev** [comment]
Hey @mmv08,
I saw that you close this merge request: https://github.com/safe-global/safe-deployments/pull/443. Now I have conflicts with my merge request after creating this pull request two weeks ago. I can open again the pull request but please merge as soon as possible.

Thanks

**Comment by mmv08** [comment]
> Hey @mmv08, I saw that you close this merge request: #443. Now I have conflicts with my merge request after creating this pull request two weeks ago. I can open again the pull request but please merge as soon as possible.
> 
> Thanks

Oops, I am sorry, somehow I missed your PR. Please ping me when you fix the conflicts and I'll try to merge it asap :pray:

**Comment by BCrypto-dev** [comment]
> > Hey @mmv08, I saw that you close this merge request: #443. Now I have conflicts with my merge request after creating this pull request two weeks ago. I can open again the pull request but please merge as soon as possible.
> > Thanks
> 
> Oops, I am sorry, somehow I missed your PR. Please ping me when you fix the conflicts and I'll try to merge it asap 🙏

Done!

**Comment by mmv08** [comment]
> > > Hey @mmv08, I saw that you close this merge request: #443. Now I have conflicts with my merge request after creating this pull request two weeks ago. I can open again the pull request but please merge as soon as possible.
> > > Thanks
> > 
> > 
> > Oops, I am sorry, somehow I missed your PR. Please ping me when you fix the conflicts and I'll try to merge it asap 🙏
> 
> Done! @mmv08

It looks like something went wrong, the diff includes changes other than adding bitrock contracts

**Comment by BCrypto-dev** [comment]
> > > > Hey @mmv08, I saw that you close this merge request: #443. Now I have conflicts with my merge request after creating this pull request two weeks ago. I can open again the pull request but please merge as soon as possible.
> > > > Thanks
> > > 
> > > 
> > > Oops, I am sorry, somehow I missed your PR. Please ping me when you fix the conflicts and I'll try to merge it asap 🙏
> > 
> > 
> > Done! @mmv08
> 
> It looks like something went wrong, the diff includes changes other than adding bitrock contracts

It is because I did a git rebase with main branch to fix the conflicts. If it is an issue I can open a pull request again @mmv08 .

**Comment by mmv08** [comment]
> > > > > Hey @mmv08, I saw that you close this merge request: #443. Now I have conflicts with my merge request after creating this pull request two weeks ago. I can open again the pull request but please merge as soon as possible.
> > > > > Thanks
> > > > 
> > > > 
> > > > Oops, I am sorry, somehow I missed your PR. Please ping me when you fix the conflicts and I'll try to merge it asap 🙏
> > > 
> > > 
> > > Done! @mmv08
> > 
> > 
> > It looks like something went wrong, the diff includes changes other than adding bitrock contracts
> 
> It is because I did a git rebase with main branch to fix the conflicts. If it is an issue I can open a pull request again @mmv08 .

It seems that rebase wasn't done correctly then. Please fix it or create a new PR, we cannot review a PR like that.

**Pull request closed without merging**
