### PR TITLE
add Venidium mainnet

### PR DESCRIPTION
**Pull request by itsfridaythen**
Added Venidium Mainnet safe contract addresses.

Chain ID: 4919
RPC Endpoint: https://rpc.venidium.io/
Block Explorer: https://evm.venidiumexplorer.com/

### CODE REVIEW

**Review by moisses89 — CHANGES_REQUESTED** [review]
chainId 4919 is mainnet.
4918 is for venidium testnet https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-4918.json

**Comment by moisses89** [comment]
> chainId 4919 is mainnet. 4918 is for venidium testnet https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-4918.json
The title or description are wrong.

**Comment by itsfridaythen** [comment]
My initial comment is wrong. The title and commit is correct.  
This Pull Request is to add Venidium Mainnet safe contract addresses.

**Review by moisses89 — APPROVED** [review]

**Comment by CrystallineButterfly** [comment]
Hi @moisses89 and @itsfridaythen Blessings to you guys, one quick question, when doing this, do you have to use yarn deploy or can you just add the chain id of the new network and the default addresses to the JSON files and then do a PR and it will work? 

Or is an ENV file and Yarn deployed required for this? 

Thank you. 

All the best-K

**Comment by moisses89** [comment]
Hi, the contracts should be deployed and we'll check it using the RPC provided.

**Comment by CrystallineButterfly** [comment]
Hi @moisses89 Ok thank you, so you use yarn deploy-all <network name> 

And do I need to use a .ENV file?

**Comment by CrystallineButterfly** [comment]
@moisses89 Are you free for a quick zoom call pls?

**Comment by moisses89** [comment]
Take a look to this :) https://github.com/safe-global/safe-contracts#deploy

**Comment by moisses89** [comment]
> @moisses89 Are you free for a quick zoom call pls?

Nope, sorry

**Comment by CrystallineButterfly** [comment]
Hi @moisses89 Thank you, so I have added the chain ID for the network im adding and added the default addresses, 

So now my step is to Yarn deploy-all (network name) ? 

And I am unsure if I should be using a .ENV file or not here, 


Thank you for your help, 

All the best-K

**Comment by moisses89** [comment]
yes, you should modify .env with your RPC and run using deploy-all custom.  
https://github.com/safe-global/safe-contracts#custom-networks

**Comment by CrystallineButterfly** [comment]
Ok, thank you @moisses89, 

So "deploy-all" is not getting recognised by the terminal,
Please could you help me fix this?

**Comment by moisses89** [comment]
Please review the readme of safe-contracts the information are there, this command is also included in the custom network section 
```
yarn deploy-all custom
```
If you have issues with that, you should create an issue in the correct project.

**Comment by CrystallineButterfly** [comment]
Yes @moisses89 Thank you, so I have followed the steps, and "deploy-all" is now not being recognised by my terminal, I will solve this and do the PR ASAP, thank you for your help.

**Pull request merged**
