### PR TITLE
Added Beam Testnet and Mainnet contracts

### PR DESCRIPTION
**Pull request by federava**
Deployed v1.3.0 and v1.4.1 on [Beam Testnet](https://chainlist.org/chain/13337) and [Beam Mainnet](https://chainlist.org/chain/4337).

Beam Testnet RPC URL: [https://subnets.avax.network/beam/testnet/rpc](https://subnets.avax.network/beam/testnet/rpc)

Beam Mainnet RPC URL: [https://subnets.avax.network/beam/mainnet/rpc](https://subnets.avax.network/beam/mainnet/rpc)

### CODE REVIEW

**Comment by federava** [comment]
@mmv08 let me know if I need to add anything else.

**Comment by MissLov3ly** [comment]
Hi!! **THANK YOU THANK YOU THANK YOU!!!**

**Comment by federava** [comment]
@mmv08 conflicts are solved

**Comment by mmv08** [comment]
> @mmv08 conflicts are solved

Please also include a minimal description of the PR. At the very least, an RPC URL to verify the deployments.

**Review by MissLov3ly — APPROVED** [review]

**Review by mmv08 — APPROVED** [review]

**Comment by mmv08** [comment]
hey @federava, could you please fix the conflicts?

**Comment by federava** [comment]
hi @mmv08, just fixed the conflicts, PR is ready to merge

**Pull request merged**
