### PR TITLE
feat: add 1.4.1 contracts for Hemi Sepolia

### PR DESCRIPTION
**Pull request by rokso**
## Add new chain

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 743111

Provide RPC URL for the chain (should be able to query atleast 3+ requests per second for automatic PR check).
- RPC_URL: https://testnet.rpc.hemi.network/rpc

Relevant information:
- https://github.com/safe-global/safe-singleton-factory/issues/770
- https://testnet.explorer.hemi.xyz/

### CODE REVIEW

**Comment by rokso** [comment]
> ```
> CompatibilityFallbackHandler deployments:
> ERROR: CompatibilityFallbackHandler not deployed at 0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99
> ```

Indeed. I didn't check addresses before. Here are the address I have got after deployment. I have followed standard procedure, I am curious why addresses are different?
```js
"CompatibilityFallbackHandler": 0xbbf7501834895288d450a5486c66031e13410F68
"CreateCall": 0xB22D635D552eC95142E2Abe3FfB859eA7d7C0316
"MultiSendCallOnly": 0xdAf12bDB02612585B4D6C2012D5bEC86EBd138E4
"MultiSend": 0x99BF7AD8C743A3240Cc861CD6E1c51FAd97dEe3B
"SafeL2": 0x0200216A26588315deD46e5451388DfC358A5bD4
"SafeMigration": 0xD76fb39525AA4E240c87C57f6DDAcA26C6D7f30A
"SafeProxyFactory": 0x8b24df6da67319eE9638a798660547D67a29f4ce
"SafeToL2Migration": 0x83df8eC8699687C18D2D4832385bcd7150D0F745
"SafeToL2Setup": 0x5941bAEf7a31933bF00B7f5Cc0Ae6abc6E41e3f0
"Safe": 0x36F86745986cB49C0e8cB38f14e948bb82d8d1A8
"SignMessageLib": 0xc162086f93fAA03AB8aEA2441fF1fbde912d5808
"SimulateTxAccessor": 0x07EfA797c55B5DdE3698d876b277aBb6B893654C
"TokenCallbackHandler": 0x0196488150f795A8Ba45a659E12e82E653d3D91D
"ExtensibleFallbackHandler": 0x2D50d8a314ED6B95056f049F25025a8290DCd46c
```

**Comment by mmv08** [comment]
> > ```
> > CompatibilityFallbackHandler deployments:
> > ERROR: CompatibilityFallbackHandler not deployed at 0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99
> > ```
> 
> Indeed. I didn't check addresses before. Here are the address I have got after deployment. I have followed standard procedure, I am curious why addresses are different?
> 
> ```js
> "CompatibilityFallbackHandler": 0xbbf7501834895288d450a5486c66031e13410F68
> "CreateCall": 0xB22D635D552eC95142E2Abe3FfB859eA7d7C0316
> "MultiSendCallOnly": 0xdAf12bDB02612585B4D6C2012D5bEC86EBd138E4
> "MultiSend": 0x99BF7AD8C743A3240Cc861CD6E1c51FAd97dEe3B
> "SafeL2": 0x0200216A26588315deD46e5451388DfC358A5bD4
> "SafeMigration": 0xD76fb39525AA4E240c87C57f6DDAcA26C6D7f30A
> "SafeProxyFactory": 0x8b24df6da67319eE9638a798660547D67a29f4ce
> "SafeToL2Migration": 0x83df8eC8699687C18D2D4832385bcd7150D0F745
> "SafeToL2Setup": 0x5941bAEf7a31933bF00B7f5Cc0Ae6abc6E41e3f0
> "Safe": 0x36F86745986cB49C0e8cB38f14e948bb82d8d1A8
> "SignMessageLib": 0xc162086f93fAA03AB8aEA2441fF1fbde912d5808
> "SimulateTxAccessor": 0x07EfA797c55B5DdE3698d876b277aBb6B893654C
> "TokenCallbackHandler": 0x0196488150f795A8Ba45a659E12e82E653d3D91D
> "ExtensibleFallbackHandler": 0x2D50d8a314ED6B95056f049F25025a8290DCd46c
> ```

what commit did you use?

**Comment by mmv08** [comment]
> > > > ```
> > > > CompatibilityFallbackHandler deployments:
> > > > ERROR: CompatibilityFallbackHandler not deployed at 0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99
> > > > ```
> > > 
> > > 
> > > Indeed. I didn't check addresses before. Here are the address I have got after deployment. I have followed standard procedure, I am curious why addresses are different?
> > > ```js
> > > "CompatibilityFallbackHandler": 0xbbf7501834895288d450a5486c66031e13410F68
> > > "CreateCall": 0xB22D635D552eC95142E2Abe3FfB859eA7d7C0316
> > > "MultiSendCallOnly": 0xdAf12bDB02612585B4D6C2012D5bEC86EBd138E4
> > > "MultiSend": 0x99BF7AD8C743A3240Cc861CD6E1c51FAd97dEe3B
> > > "SafeL2": 0x0200216A26588315deD46e5451388DfC358A5bD4
> > > "SafeMigration": 0xD76fb39525AA4E240c87C57f6DDAcA26C6D7f30A
> > > "SafeProxyFactory": 0x8b24df6da67319eE9638a798660547D67a29f4ce
> > > "SafeToL2Migration": 0x83df8eC8699687C18D2D4832385bcd7150D0F745
> > > "SafeToL2Setup": 0x5941bAEf7a31933bF00B7f5Cc0Ae6abc6E41e3f0
> > > "Safe": 0x36F86745986cB49C0e8cB38f14e948bb82d8d1A8
> > > "SignMessageLib": 0xc162086f93fAA03AB8aEA2441fF1fbde912d5808
> > > "SimulateTxAccessor": 0x07EfA797c55B5DdE3698d876b277aBb6B893654C
> > > "TokenCallbackHandler": 0x0196488150f795A8Ba45a659E12e82E653d3D91D
> > > "ExtensibleFallbackHandler": 0x2D50d8a314ED6B95056f049F25025a8290DCd46c
> > > ```
> > 
> > 
> > what commit did you use?
> 
> I have deployed from main branch latest commit 129f02cdd72b7af806d90a622959f42d6171bd70, I guess I should have used 1.4.1. Should I deploy again using 1.4.1?

Correct

**Comment by rokso** [comment]
@mmv08 I have deployed 1.4.1 contract, can you try verification again?

**Comment by remedcu** [comment]
Could you also please deploy the safe migration contracts? Use the tag: [v1.4.1-3](https://github.com/safe-global/safe-smart-account/tree/v1.4.1-3) for deployment

**Review by remedcu — APPROVED** [review]

**Pull request merged**
