### PR TITLE
Add 1.4.1 contracts for Haust testnet

### PR DESCRIPTION
**Pull request by UrfinDeuce**
Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 1570754601
Provide RPC URL for the chain (should be able to query at least 3+ requests per second for automatic PR check).
- RPC_URL: https://rpc-test.haust.network

Relevant information:
- safe-singleton-factory issue: https://github.com/safe-global/safe-singleton-factory/issues/710
- block explorer: https://haust-testnet-blockscout.eu-north-2.gateway.fm/

### CODE REVIEW

**Comment by remedcu** [comment]
Could you also deploy the Safe Migration contracts?

**Comment by UrfinDeuce** [comment]
> Could you also deploy the Safe Migration contracts?

I have SafeMigration and SafeToL2Migration contracts, do I need to add them? What should I do with SafeToL2Setup and TokenCallbackHandler?

**Comment by remedcu** [comment]
> I have SafeMigration and SafeToL2Migration contracts, do I need to add them? What should I do with SafeToL2Setup and TokenCallbackHandler?

Please add the entry for all the contracts mentioned [here](https://github.com/safe-global/safe-deployments/tree/main/src/assets/v1.4.1) if you have already deployed.

**Comment by UrfinDeuce** [comment]
> > I have SafeMigration and SafeToL2Migration contracts, do I need to add them? What should I do with SafeToL2Setup and TokenCallbackHandler?
> 
> Please add the entry for all the contracts mentioned [here](https://github.com/safe-global/safe-deployments/tree/main/src/assets/v1.4.1) if you have already deployed.

added

**Review by remedcu — APPROVED** [review]

**Pull request merged**
