### PR TITLE
feat: add autonomys testnet 1.3.0 assets info

### PR DESCRIPTION
**Pull request by DenSmolonski**
## Add new chain

> Template to provide information about the new chain. Only add extra information in the bottom section. Ensure that the contracts are deployed on the chain, if not deploy with [safe-contracts](https://github.com/safe-global/safe-contracts). Only **one** chain ID, **one** Safe version and **one** deployment type per PR. This entire paragraph should be deleted.

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 490000(0x77a10)

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
- RPC_URL: https://nova-0.gemini-3h.subspace.network/ws

Relevant information:
https://nova.subspace.network/

### CODE REVIEW

**Comment by mmv08** [comment]
Could you please pull from main so the review script is up to date?

**Comment by DenSmolonski** [comment]
@mmv08 branch updated.

**Comment by mmv08** [comment]
> @mmv08 branch updated.

I think you merged the wrong main branch (from your fork)

**Comment by mmv08** [comment]
> > @mmv08 branch updated.
> 
> I think you merged the wrong main branch (from your fork)

Never mind, we found a bug with the script and are working on fixing it.

**Comment by remedcu** [comment]
Apologies for the back and forth, could you please merge the `main` branch again? 😰

**Comment by DenSmolonski** [comment]
@remedcu @mmv08 Updated. Sorry for long response.

**Review by nlordell — APPROVED** [review]

**Pull request merged**
