### PR TITLE
add Susono network

### PR DESCRIPTION
**Pull request by steliyannedev**

### CODE REVIEW

**Comment by steliyannedev** [comment]
based on #179

**Comment by steliyannedev** [comment]
using Avalance subnet this is the reason the addresses are not deployed deteriminalisitc deployment, if that is an issue I would redeploy them as requested

**Comment by mikhailxyz** [comment]
> using Avalance subnet this is the reason the addresses are not deployed deteriminalisitc deployment, if that is an issue I would redeploy them as requested

please do, this package is a collection of deterministic deployments

**Comment by steliyannedev** [comment]
> > using Avalance subnet this is the reason the addresses are not deployed deteriminalisitc deployment, if that is an issue I would redeploy them as requested
> 
> please do, this package is a collection of deterministic deployments

could you please provide me with a little info or give me some leads as of how can I do that with network that have replay protection?

**Comment by mikhailxyz** [comment]
> > > using Avalance subnet this is the reason the addresses are not deployed deteriminalisitc deployment, if that is an issue I would redeploy them as requested
> > 
> > 
> > please do, this package is a collection of deterministic deployments
> 
> could you please provide me with a little info or give me some leads as of how can I do that with network that have replay protection?

https://github.com/safe-global/safe-contracts#replay-protection-eip-155

**Comment by Uxio0** [comment]
I'm closing this issue due to inactivity

**Pull request closed without merging**
