### PR TITLE
feat: add bevm testnet(11503)

### PR DESCRIPTION
**Pull request by icodezjb**
## Add new chain

> Template to provide information about the new chain. Only add extra information in the bottom section. Ensure that the contracts are deployed on the chain, if not deploy with [safe-contracts](https://github.com/safe-global/safe-contracts). Only **one** chain ID, **one** Safe version and **one** deployment type per PR. This entire paragraph should be deleted.

Please fill the following form:

Provide the Chain ID (Only 1 chain id per PR).
- Chain_ID: 11503

Provide RPC URL for the chain (should be able to query atleast 10 requests per minute for automatic PR check).
- RPC_URL: https://testnet.bevm.io

Relevant information:
Block explorer: https://scan-testnet.bevm.io/

### CODE REVIEW

**Comment by remedcu** [comment]
Could you resolve the conflicts and use this [PR Template](https://github.com/safe-global/safe-deployments/blob/main/.github/PULL_REQUEST_TEMPLATE.md)?

**Comment by icodezjb** [comment]
> Could you resolve the conflicts and use this [PR Template](https://github.com/safe-global/safe-deployments/blob/main/.github/PULL_REQUEST_TEMPLATE.md)?

Done

**Comment by remedcu** [comment]
Could you please pull from the `main` branch, so the review script is up to date?

**Review by nlordell — CHANGES_REQUESTED** [review]
Please rebase this PR.

**Review by nlordell — APPROVED** [review]

**Review by nlordell — APPROVED** [review]

**Pull request merged**
