### PR TITLE
Add Scroll Alpha Testnet

### PR DESCRIPTION
**Pull request by pajicf**

### CODE REVIEW

**Comment by pajicf** [comment]
Of course

RPC: https://alpha-rpc.scroll.io/l2
Chainlist: https://chainlist.org/chain/534353

**Comment by moisses89** [comment]
> Of course
> 
> RPC: https://alpha-rpc.scroll.io/l2 Chainlist: https://chainlist.org/chain/534353

If you create an issue related with this PR https://github.com/safe-global/safe-deployments/issues/new?assignees=&labels=%5Benhancement%5D&template=new_chain.yaml&title=%5BNew+chain%5D%3A+ and fill all  would be perfect!

**Review by moisses89 — APPROVED** [review]
Looks good to me!

**Comment by pajicf** [comment]
> > Of course
> > RPC: https://alpha-rpc.scroll.io/l2 Chainlist: https://chainlist.org/chain/534353
> 
> @pajicf If you create an issue related with this PR https://github.com/safe-global/safe-deployments/issues/new?assignees=&labels=%5Benhancement%5D&template=new_chain.yaml&title=%5BNew+chain%5D%3A+ and provide all the necessary information, would be perfect!

Of course, issue created [here](https://github.com/safe-global/safe-deployments/issues/216)

**Comment by pajicf** [comment]
> Looks good to me!

Thank you!

**Comment by pajicf** [comment]
Do you maybe have an estimate when will new package version of the repo be deployed?

**Comment by pajicf** [comment]
> > Do you maybe have an estimate when will new package version of the repo be deployed?
> 
> Looks refreshed here: https://www.npmjs.com/package/@gnosis.pm/safe-singleton-factory
> 
> Thx so much, everyone! :)

That was quick! Thanks everyone!

**Pull request merged**
