### PR TITLE
Add Boba Avax, Boba BNB and Boba BNB testnet

### LINKED ISSUE #192: [New chain]: Boba BNB testnet
### ChainId

9728

### Chainlist

https://chainlist.org/chain/9728

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

wss://replica-wss.testnet.bnb.boba.network 
https://replica.testnet.bnb.boba.network
https://testnet.bnb.boba.network
http://gateway.testnet.bnb.boba.network
https://blockexplorer.testnet.bnb.boba.network

### LINKED ISSUE #193: [New Chain]: Boba Avalanche
### ChainId

43288

### Chainlist

https://chainlist.org/chain/43288

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

https://avax.boba.network
https://replica.avax.boba.network 
wss://replica-wss.avax.boba.network
http://gateway.testnet.avax.boba.network
https://blockexplorer.testnet.avax.boba.network

### LINKED ISSUE #194: [New chain]: Boba BNB
### ChainId

56288

### Chainlist

https://chainlist.org/chain/56288

### Contract deployed

- [X] I confirm that the contracts are deployed

### Version of contracts deployed

v1.3.0

### Relevant information

wss://replica-wss.bnb.boba.network
https://bnb.boba.network 
https://replica.bnb.boba.network
https://gateway.bnb.boba.network
https://blockexplorer.bnb.boba.network

### PR DESCRIPTION
**Pull request by InoMurko**
As per: https://github.com/safe-global/safe-singleton-factory/pull/79/files

Boba on testnet Avax is sadly broken.

### CODE REVIEW

**Comment by moisses89** [comment]
Hey @InoMurko, could you create an issue to add [new chain](https://github.com/safe-global/safe-deployments/issues/new?assignees=&labels=%5Benhancement%5D&template=new_chain.yaml&title=%5BNew+chain%5D%3A+)? some information is required to review.

**Comment by InoMurko** [comment]
> Hey @InoMurko, could you create an issue to add [new chain](https://github.com/safe-global/safe-deployments/issues/new?assignees=&labels=%5Benhancement%5D&template=new_chain.yaml&title=%5BNew+chain%5D%3A+)? some information is required to review.  

Sure. Does this prevent merging this PR?

**Comment by moisses89** [comment]
> > Hey @InoMurko, could you create an issue to add [new chain](https://github.com/safe-global/safe-deployments/issues/new?assignees=&labels=%5Benhancement%5D&template=new_chain.yaml&title=%5BNew+chain%5D%3A+)? some information is required to review.  
> 
> Sure. Does this prevent merging this PR?
It is a helpful information to review this PR like RPC URLs and this type of things. I can see that you have three chains in this PR, then you can add the other chains info in additional information form. I'll review this PR after the issue, ping me when ready.

**Comment by InoMurko** [comment]
> > > Hey @InoMurko, could you create an issue to add [new chain](https://github.com/safe-global/safe-deployments/issues/new?assignees=&labels=%5Benhancement%5D&template=new_chain.yaml&title=%5BNew+chain%5D%3A+)? some information is required to review.
> > 
> > 
> > Sure. Does this prevent merging this PR?
> 
> It is a helpful information to review this PR like RPC URLs and this type of things. I can see that you have three chains in this PR, then you can add the other chains info in additional information form. I'll review this PR after the issue, ping me when ready.

Issues open!

**Review by moisses89 — APPROVED** [review]
Looks good to me!

**Pull request merged**
